# Generated by Django 5.2.3 on 2025-06-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
